import Head from "next/head";
import { Grid, Column, TextArea, Form } from "@carbon/react";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { MathpixMarkdown, MathpixLoader } from "mathpix-markdown-it";

export default function Home() {

  const [markdown, setMarkdown] = useState("")
  
  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div>
      <Form>
        <Grid style={{ height: "100vh" }}>
          <Column lg={8} md={4} sm={4}>
            <TextArea
              cols={50}
              helperText=""
              id="locality"
              invalidText="Optional field"
              labelText="Location (optional)"
              placeholder="New Delhi"
              rows={25}
              onChange={(e) => {
                setMarkdown(e.target.value);
              }}
              style={{ height: "100%" }}
            />
          </Column>
          <Column
            lg={8}
            md={4}
            sm={4}
            style={{
              height: "85vh",
              overflowX: "scroll",
              marginBlock: "2rem",
            }}
          >
            <MathpixLoader>
              <MathpixMarkdown text={markdown} />
            </MathpixLoader>
          </Column>
        </Grid>
      </Form>
    </div>
  </div>
  )
}
